### ISSUE TITLE
undecoded messages

### ISSUE THREAD

**Issue by TLeconte** [szpajder/libacars#1]
First thanks for this lib and your work to include it in [acarsdec](https://github.com/Tleconte/acarsdec)

I have a question:
I see in acars this kind of message:
`#M1B/BA SOUCAYA.CC1.I-NDMJ60412240491075DA`
That is perfectly decoded by libacars

But I see too messages that really look like FANS-1/A messagebut  that are not decoded:
'#M1B/B0 SOUCAYA.AFN/FMHNOS492,.I-NDMJ,,182449/FRP0A481`

It could be normal, I don't really know ARINC 622

**Comment by szpajder** [comment]
I haven't yet written a parser for AFN messages because I was lazy ;) and it's just a simple, comma-delimited format, where almost everything is visible and understandable at a glance (NOS492 is the flight number, I-NDMJ is the reg number, next one is probably the timestamp). I may code this up one day, however I'd rather focus on binary message types first.

**Comment by TLeconte** [comment]
ok  I just feared a bug
